name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: "https://registry.npmjs.org"

      # 🔧 Limpia cualquier config previa de npm y fuerza el registry público
      - name: Reset npm config
        run: |
          npm config delete registry || true
          npm config delete @*registry || true
          npm config delete always-auth || true
          rm -f ~/.npmrc
          echo "registry=https://registry.npmjs.org/" > .npmrc
          npm cache clean --force

      # 🛡️ Instalación con reintento por si el registry tiene hipo momentáneo
      - name: Install dependencies
        run: |
          set -e
          ATTEMPTS=3
          for i in $(seq 1 $ATTEMPTS); do
            if [ -f package-lock.json ]; then
              npm ci --no-audit --no-fund && break || true
            else
              npm i --no-audit --no-fund && break || true
            fi
            echo "Install attempt $i/$ATTEMPTS failed. Retrying in 5s..."
            sleep 5
          done

      - name: Lint
        run: npm run lint

      - name: Test (Vitest) with coverage
        run: npm run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: ignore

      - name: Build (Vite)
        run: npm run build
